package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"http-go-sandbox/graph/db"
	"http-go-sandbox/graph/model"
	"strconv"
)

// Authors is the resolver for the authors field.
func (r *queryResolver) Authors(ctx context.Context) ([]*model.Author, error) {
	authors, err := db.ListAuthors()

	if err != nil {
		return nil, err
	}

	for _, author := range authors {
		r.authors = append(r.authors, &model.Author{
			ID:   strconv.FormatInt(author.ID, 10),
			Name: author.Name,
		})
	}
	return r.authors, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
